### ISSUE TITLE
Wrong property type

### ISSUE THREAD

**Issue by freekzero** [docusign/docusign-php-client#30]
DocuSign\eSign\Model\SignHere::scale_value is set as type object but should be string per https://www.docusign.com/p/RESTAPIGuide/Content/REST%20API%20References/Tabs/Sign%20Here%20Tab.htm

Using object causes a crash when a template with a SignHere is serialized. Changing scale_value to string fixed the issue.

Note this same issue appears in other SDKs, or at least in the Java SDK anyway, and I presume across all SDKs that use the Swagger base point.

**Comment by gsnavin** [comment]
@freekzero First off, sorry for the delayed response.

You are referring to our legacy documentation. Please refer to our new API documentation
https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/create/#request

Also we have updated the PHP client since you last referred, please check it out and let me know if you have any questions.
