### ISSUE TITLE
Serializer issue: Class '\DocuSign\eSign\Model\array' not found

### ISSUE THREAD

**Issue by urdhvatech** [docusign/docusign-php-client#70]
When I add a Dropdown on the DocuSign template and try to get the template details using api method

![docusignapi-error1](https://user-images.githubusercontent.com/5037993/53472629-32967900-3a8e-11e9-93d9-e052e77f56b4.png)

`$templateApi = new DocuSign\eSign\Api\TemplatesApi($this->getApiClient());
$oEnvelopeTemplate = $templateApi->get($this->getAccountId(), $rs_template_id);`

I get the error

Fatal error: Class '\DocuSign\eSign\Model\array' not found in \esign-client\src\ObjectSerializer.php on line 281

**Comment by LarryKlugerDS** [comment]
Hi @urdhvatech,
I apologize for the slow response.

Thank you for the bug report. This is a known problem, see [issue 58](https://github.com/docusign/docusign-php-client/issues/58). It is covered by internal ticket DCM-2915

The Engineering group has told me that they do have the bug on their roadmap to fix. Unfortunately we don't have a specific fix date yet. 

In the meantime, as a work-around, you can call the API directly from PHP instead of using the SDK.

I will close this issue since it is a duplicate for [issue 58](https://github.com/docusign/docusign-php-client/issues/58).

Thank you,
Larry

**Comment by christiaanschmid** [comment]
@larrykluger This issue seems to still remain today.

I can replicate this error with a Dropdown field on my document and the following code

```php
$templateApi = new TemplatesApi($apiClient);
$tabs = $templateApi->getDocumentTabs($accountId, $documentId, $templateId);
```

This results in: `PHP Error:  Class '/DocuSign/eSign/Model/array' not found`

When looking at the Tabs model, there is a `swaggerTypes` array containing the property to type mappings. For `list_tabs` the type is `\DocuSign\eSign\Model\array[]`. That model doesn't seem to exist in the `docusign\esign-client\src\Model` directory. If I change `array[]` to `ModelList[]` no error is thrown.

I looked into [issue 58](https://github.com/docusign/docusign-php-client/issues/58), but it looks like that only resolved the issue around `List` and not `array`.

**Comment by RiaanBez** [comment]
Hi 

I am also experiencing this problem would like to be kept in the loop with the ETA on the fix

Best Regards
Riaan
