### ISSUE TITLE
Example use of LoginInformation fails on Count()

### ISSUE THREAD

**Issue by plweller3** [docusign/docusign-php-client#71]
While the library itself seems to work with PHP 7.2, the use of count() on an instantiation of LoginInformation fails.  The fix is to implement the Countable interface on LoginInformation:

          class LoginInformation implements ArrayAccess, \Countable

And then add a count method in the class to access container:

          public function count() 
         { 
                return count($this->container); 
          }

**Comment by LarryKlugerDS** [comment]
Hi @plweller3,

Did you know that the LoginInformation SDK method cannot be used with OAuth authentication methods? And that only OAuth authentication should be used for new integrations with DocuSign?

Unfortunately the LoginInformation method is poorly named.

We have PHP code examples for both [OAuth Authorization Code Grant](https://github.com/docusign/eg-03-php-auth-code-grant) (when the user is present) and [OAuth JWT Grant](https://github.com/docusign/eg-01-php-jwt). 

Both of those examples also show how to use the [OAuth::getUserInfo](https://developers.docusign.com/esign-rest-api/guides/authentication/user-info-endpoints) method instead of the obsolete LoginInformation method. 

Thanks,
Larry

**Comment by LarryKlugerDS** [comment]
I have created internal ticket DCM-3190 for this request.

**Comment by LarryKlugerDS** [comment]
Since LoginInformation (and the related legacy authentication techniques) have been deprecated for a couple of years now, I'm closing this issue as won't fix.
